// Auto-generated from 具身智能企业_IPO分类及融资估值表-2.xlsx, then lightly corrected with public-source checks.
window.dashboardIpoData = [
  { id: 1, category: "四足", company: "云深处科技", stage: "正式受理排队", board: "科创板", business: "四足机器人、人形机器人及核心关节", preIpoFunding: 10, primaryValuation: 139 },
  { id: 2, category: "人形", company: "魔法原子", stage: "拟IPO筹备", board: "未明确", business: "通用人形机器人、四足机器狗、灵巧手、关节模组及原子万象场景大模型", preIpoFunding: 10, primaryValuation: 30 },
  { id: 3, category: "人形", company: "傅利叶智能", stage: "拟IPO筹备", board: "科创板", business: "康复机器人及GR系列通用人形机器人", preIpoFunding: 16, primaryValuation: 80 },
  { id: 4, category: "人形", company: "松延动力", stage: "拟IPO筹备", board: "港股", business: "双足人形机器人、仿生人形机器人及消费级人形机器人", preIpoFunding: 20, primaryValuation: "未披露" },
  { id: 5, category: "人形", company: "众擎机器人", stage: "辅导备案/已递表", board: "港股", business: "通用人形机器人、本体、核心零部件及运动控制", preIpoFunding: 27.5, primaryValuation: 100 },
  { id: 6, category: "人形", company: "逐际动力", stage: "辅导备案/已递表", board: "港股", business: "全尺寸人形机器人及TRON多形态具身机器人", preIpoFunding: 35, primaryValuation: 150 },
  { id: 7, category: "人形", company: "乐聚机器人", stage: "正式受理排队", board: "创业板", business: "夸父、鲁班、Aelos系列全尺寸及中小型人形机器人", preIpoFunding: 18.5, primaryValuation: 43.27 },
  { id: 8, category: "人形", company: "宇树科技", stage: "近期已上市", board: "科创板", business: "G1、H1、R1人形机器人及高性能四足机器人、关节与运动控制", preIpoFunding: 15.7, primaryValuation: 127 },
  { id: 9, category: "通用全栈", company: "星动纪元", stage: "拟IPO筹备", board: "港股", business: "ERA-42 VLA大模型、具身大脑、运动控制与人形本体协同研发", preIpoFunding: 45, primaryValuation: 200 },
  { id: 10, category: "通用全栈", company: "原力灵机", stage: "拟IPO筹备", board: "港股", business: "DM系列具身原生VLA模型，面向真实物理世界的感知、推理与动作生成", preIpoFunding: 20, primaryValuation: 200 },
  { id: 11, category: "通用全栈", company: "跨维智能", stage: "拟IPO筹备", board: "港股", business: "物理AI世界模型、Sim2Real VLA、DexVerse引擎及跨本体操作智能", preIpoFunding: 15, primaryValuation: 100 },
  { id: 12, category: "通用全栈", company: "星尘智能", stage: "拟IPO筹备", board: "未明确", business: "Lumo端到端全身VLA基座模型、DuoCore部署框架与绳驱AI机器人", preIpoFunding: 10, primaryValuation: 100 },
  { id: 13, category: "通用全栈", company: "千寻智能", stage: "拟IPO筹备", board: "港股", business: "Spirit VLA与World Model结合的具身大模型，覆盖数据、模型与智能体闭环", preIpoFunding: 50, primaryValuation: 200 },
  { id: 14, category: "通用全栈", company: "苏度科技", stage: "拟IPO筹备", board: "未明确", business: "3D世界模型、Real2Sim2Real训练体系与Sudo R1通用操作机器人", preIpoFunding: 34, primaryValuation: 200 },
  { id: 15, category: "通用全栈", company: "自变量", stage: "辅导备案/已递表", board: "港股", business: "WALL-A操作大模型，统一感知、理解、决策与高精度动作控制", preIpoFunding: 45, primaryValuation: 200 },
  { id: 16, category: "通用全栈", company: "智平方", stage: "辅导备案/已递表", board: "港股", business: "AlphaBrain及全域全身VLA模型，面向跨场景机器人操作与泛化", preIpoFunding: 60, primaryValuation: 200 },
  { id: 17, category: "通用全栈", company: "星海图", stage: "辅导备案/已递表", board: "港股", business: "VLA基础模型、世界模型训练数据链路及机器人本体验证闭环", preIpoFunding: 50, primaryValuation: 200 },
  { id: 18, category: "通用全栈", company: "智元机器人", stage: "辅导备案/已递表", board: "港股", business: "GO-1具身基座模型、机器人数据集、多形态本体与场景应用闭环", preIpoFunding: 35, primaryValuation: 150 },
  { id: 19, category: "通用全栈", company: "银河通用", stage: "辅导备案/已递表", board: "港股", business: "VLA具身大模型、大小脑控制、世界模型数据闭环与轮式双臂机器人", preIpoFunding: 60, primaryValuation: 210 },
  { id: 20, category: "通用全栈", company: "优必选", stage: "近期已上市", board: "港股", business: "Walker系列人形机器人，覆盖本体、运动控制、感知决策与群体协同", preIpoFunding: 56.1, primaryValuation: 312 },
  { id: 21, category: "产业链上下游", company: "灵心巧手", stage: "拟IPO筹备", board: "港股", business: "LinkerHand高自由度灵巧手及具身操作技能平台", preIpoFunding: 35, primaryValuation: 200 },
  { id: 22, category: "产业链上下游", company: "蓝芯机器人", stage: "拟IPO筹备", board: "意向A股", business: "3D视觉传感器、工业移动机器人及场内物流系统", preIpoFunding: 5.6, primaryValuation: 15 },
  { id: 23, category: "产业链上下游", company: "梅卡曼德", stage: "近期已上市", board: "港股主板", business: "工业3D相机、机器视觉软件及“眼脑手”机器人平台", preIpoFunding: 40, primaryValuation: 85 },
  { id: 24, category: "产业链上下游", company: "光轮智能", stage: "拟IPO筹备", board: "港股", business: "物理仿真引擎、合成数据工厂及机器人评测工具", preIpoFunding: 30, primaryValuation: 150 },
  { id: 25, category: "产业链上下游", company: "辰星技术", stage: "辅导备案/已递表", board: "港股", business: "并联、SCARA、协作及具身工业机器人", preIpoFunding: 4.07, primaryValuation: 25 },
  { id: 26, category: "产业链上下游", company: "普渡机器人", stage: "拟IPO筹备", board: "港股", business: "商用配送、清洁、工业物流及类人形机器人", preIpoFunding: ">20", primaryValuation: ">100" },
  { id: 27, category: "产业链上下游", company: "卡诺普", stage: "正式受理排队", board: "港股", business: "焊接工业机器人、协作机器人及控制系统", preIpoFunding: 3, primaryValuation: 21.05 },
  { id: 28, category: "产业链上下游", company: "优艾智合", stage: "正式受理排队", board: "港股", business: "工业AMR、移动操作机器人、FabriX工业具身模型", preIpoFunding: 5.9, primaryValuation: 20.8 },
  { id: 29, category: "产业链上下游", company: "斯坦德", stage: "正式受理排队", board: "港股", business: "工业AMR、调度系统及智能移动机器人解决方案", preIpoFunding: 9.8, primaryValuation: 21 },
  { id: 30, category: "产业链上下游", company: "越疆科技", stage: "正式受理排队", board: "创业板", business: "协作机器人、工业机械臂及自动化解决方案", preIpoFunding: 6.8, primaryValuation: 120 },
  { id: 31, category: "产业链上下游", company: "睿尔曼智能", stage: "辅导备案/已递表", board: "创业板", business: "超轻量机械臂、一体化关节模组及轮式机器人", preIpoFunding: 5, primaryValuation: 32 },
  { id: 32, category: "产业链上下游", company: "珞石机器人", stage: "近期已上市", board: "港股", business: "轻量化协作机器人、工业机械臂、力控与机器人自动化解决方案", preIpoFunding: 7.53, primaryValuation: 105.43 },
];
window.dashboardIpoStages = ["拟IPO筹备", "辅导备案/已递表", "正式受理排队", "近期已上市"];
window.dashboardIpoCategories = ["四足", "人形", "通用全栈", "产业链上下游"];
